# Generated by Django 6.0.5 on 2026-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Headphone', 'Headphone'), ('Watch', 'Watch'), ('Accessory', 'Accessory')], default='Phone', max_length=50),
            preserve_default=False,
        ),
    ]
