# Generated by Django 6.0.5 on 2026-06-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphones', 'Smartphones'), ('laptops', 'Laptops'), ('beauty', 'Beauty'), ('fragrances', 'Fragrances'), ('furniture', 'Furniture'), ('groceries', 'Groceries'), ('mens-shirts', 'Mens Shirts'), ('womens-dresses', 'Womens Dresses'), ('sports-accessories', 'Sports'), ('vehicle', 'Vehicle')], max_length=50),
        ),
    ]
